image: cardcorp/r-java

pipelines:
  default:
    - step:
        script:
          - cd /opt/atlassian/pipelines/agent/build
          - Rscript -e 'install.packages("tidyverse")'
          - Rscript -e 'devtools::install_deps(".", dependencies=TRUE, upgrade=FALSE)'
          - Rscript -e 'devtools::build()'
          - Rscript -e 'devtools::install(upgrade_dependencies = FALSE)'
          - Rscript -e 'devtools::check()'